// Generated by Wrangler on Wed Aug 14 2024 03:38:02 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	KEYSTATIC_REPO_OWNER: string;
	KEYSTATIC_REPO_NAME: string;
	KEYSTATIC_GITHUB_CLIENT_ID: string;
	KEYSTATIC_GITHUB_CLIENT_SECRET: string;
	KEYSTATIC_SECRET: string;
	PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
}
